# Generated by Django 5.1.5 on 2025-01-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='bus',
            field=models.ManyToManyField(related_name='reservation', to='bus.bus'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guset',
            field=models.ManyToManyField(related_name='reservation', to='bus.guests'),
        ),
    ]
